# Generated by Django 5.1.3 on 2024-11-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effectiveness',
            fields=[
                ('EffID', models.IntegerField(primary_key=True, serialize=False)),
                ('explanation', models.CharField(max_length=20)),
                ('ex_detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('memID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuID', models.AutoField(primary_key=True, serialize=False)),
                ('tealeaf', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=10000)),
                ('origin', models.CharField(max_length=10)),
                ('effID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('order_basketID', models.CharField(max_length=10)),
                ('order_menuID', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuID', models.IntegerField(default=0, unique=True)),
                ('basketID', models.ForeignKey(db_column='basketID', on_delete=django.db.models.deletion.CASCADE, to='teashop.memberinfo')),
            ],
        ),
    ]
